Fix race in tests
TestWire.Connection can be null when new test starts with unfinished activities.

System.NullReferenceException: Object reference not set to an instance of an object.
|E| JetBrains.Collections.Viewable.SingleThreadScheduler.Server
   at Test.RdFramework.Components.TestWire.<TransmitOneMessage>b__17_0()
   at JetBrains.Collections.Viewable.SchedulerEx.InvokeOrQueue(IScheduler sc, Action action)
   at Test.RdFramework.Components.TestWire.TransmitOneMessage()
   at Test.RdFramework.Components.TestWire.<TransmitAllMessages>b__18_0()
   at JetBrains.Collections.Viewable.SingleThreadScheduler.ExecuteOneAction(Boolean blockIfNoActionAvailable)